services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: rest_with_spring
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - josenatal-network

  rest_with_spring_boot:
    image: josenatal/rest-with-spring-boot
    restart: always
    build: ./rest-with-spring-boot
    working_dir: /rest-with-spring-boot
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/rest_with_spring
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - josenatal-network

networks:
  josenatal-network:
    driver: bridge

#build application: mvn clean package -DskipTests
#start do container:docker compose up -d
#stop do container: docker compose down
