spring:
  application:
    name: rest-with-spring-boot
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_spring
    username: usuario
    password: senha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: none
    show-sql: false
    open-in-view: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true